language: go
go:
  - 1.6
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tools/godep
  - go get github.com/tcnksm/ghr
  - go get github.com/onuryilmaz/gazeteci
  - go get ./...
after_success:
  - gox -output "dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
  - ghr --username onuryilmaz --token $GITHUB_TOKEN --replace 0.0.1 dist/
